branch-defaults:
  default:
    environment: hkAppThree-env-dev
    group_suffix: null
global:
  application_name: hkAppThree-env
  default_ec2_keyname: aws-eb
  default_platform: Python
  default_region: us-west-2
  profile: null
  sc: null
